app/routes/api.py
import stripe
from flask import current_app, Blueprint, request, redirect, url_for, render_template
from ..models import Product
from .. import db

api_bp = Blueprint('api_bp', __name__)

@api_bp.route('/products', methods=["POST"])
def add_product():
    name = request.form["name"]
    description = request.form["description"]
    price = int(request.form["price"])

    stripe_secret_key = current_app.config["STRIPE_SECRET_KEY"]
    stripe.api_key = stripe_secret_key

    # create product on Stripe
    stripe_product = stripe.Product.create(name=name, description=description)

    # create a price object on Stripe
    stripe_price = stripe.Price.create(
        product=stripe_product.id,
        unit_amount=price,
        currency='usd',
    )

    # store stripe product and price ids to db
    new_product = Product(
        name=name,
        description=description,
        price=price,
        stripe_product_id=stripe_product.id,
        stripe_price_id=stripe_price.id,
    )

    db.session.add(new_product)
    db.session.commit()
    return redirect(url_for("frontend_bp.index"))

app/routes/frontend.py
from flask import Blueprint, render_template
from ..utils.database import get_all_products

frontend_bp = Blueprint('frontend_bp', __name__)

@frontend_bp.route("/")
def index():
    products = get_all_products()
    return render_template("list_products.html", products=products)

@frontend_bp.route('/products')
def add_product_view():
    return render_template('add_product.html')

@frontend_bp.route("/success")
def success():
    return render_template("success.html")

@frontend_bp.route("/cancelled")
def cancelled():
    return render_template("cancelled.html")

app/templates/add_product.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Add Supa Tee</h1>
        <div class="columns is-centered">
            <div class="column is-half-desktop is-two-thirds-tablet is-full-mobile">
                <form action="{{ url_for('api_bp.add_product') }}" method="POST">
                    <div class="field">
                        <label for="productName" class="label">Product Name</label>
                        <div class="control">
                            <input type="text" class="input" id="productName" name="name" placeholder="Enter product name" required>
                        </div>
                    </div>
                    <div class="field">
                        <label for="productDescription" class="label">Product Description</label>
                        <div class="control">
                            <textarea class="textarea" id="productDescription" name="description" placeholder="Enter product description" required></textarea>
                        </div>
                    </div>
                    <div class="field">
                        <label for="productPrice" class="label">Price in cents</label>
                        <div class="control">
                            <input type="number" class="input" id="productPrice" name="price" placeholder="Enter price" required>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <button type="submit" class="button is-primary">Add Product</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/add_products.html
{% extends "base.html" %}

{% block content %}
<form action="{{ url_for('create_products') }}" method="POST">
    <input type="text" name="name" placeholder="Product Name" required>
    <textarea name="description" placeholder="Product Description" required></textarea>
    <input type="number" name="price" placeholder="Price in cents" required>
    <button type="submit">Add Product</button>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Supa Tees</title>
        <!-- Import Bulma CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        <!-- Import Stripe -->
        <script src="https://js.stripe.com/v3/"></script>
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
    </head>
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>  
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>      
    </body>
</html>

app/templates/cancelled.html
{% extends "base.html" %}

{% block content %}
    <section class="section">
        <div class="container">
        <p>Uh-oh! Your payment was cancelled.</p>
        </div>
    </section>
{% endblock %}

app/templates/list_products.html
{% extends "base.html" %}

{% block content %}
<h1 class="title has-text-centered">Supa Tees</h1>
<div class="has-text-centered">
    <a href="{{ url_for('frontend_bp.add_product_view') }}" class="button is-primary mb-4">Create New Product</a>
</div>
<div class="columns is-multiline is-centered product-list">
    {% for product in products %}
    <div class="column is-one-quarter">
        <div class="box">
            <article class="media">
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>{{ product.name }}</strong>
                            <br>
                            {{ product.description }}
                            <br>
                            <strong>Price:</strong> ${{ product.price / 100 }}
                        </p>
                    </div>
                    <div class="has-text-centered">
                        <button class="button is-primary purchase-button" data-id="{{ product.id }}" data-stripe-price-id="{{ product.stripe_price_id }}">Buy Now</button>
                    </div>
                </div>
            </article>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/success.html
{% extends "base.html" %}

{% block content %}
    <section class="section">
        <div class="container">
        <p>Your payment was a success!</p>
        </div>
    </section>
{% endblock %}